### ISSUE TITLE
As a customer, I want to be able to have the website suggest meeting times based off of my and other's Google calendar.

### ISSUE THREAD

**Issue by jonathanwong113** [cs130-w22/Group-A6#1]
## Epic
The user(s) needs to be able to sync up their Google calendar and have the software read their availability. It also needs to produce a list of potential meeting times for the meeting host to choose from.

## User Stories
- [ ] As a customer, I needs to be able to link their Google Calendar to the website
- [x] As the meeting host, I want to have a list of meeting times suggested to them based off everyone's calendar availability.
- [ ] As the meeting host, I want to be able to invite others to my meeting.
