### ISSUE TITLE
As a customer, I want to be able to use a mobile app to easily schedule meetings with other people through a simple user interface

### ISSUE THREAD

**Issue by sahenrai** [cs130-w22/Group-A6#3]
## Epic
As a customer, I want to be able to use a mobile app to easily schedule meetings with other people through a simple user interface
## User Stories
- [ ] As a customer, I wish to be able to connect my Google Calendar into this app to easily find times to meet
- [ ] As a customer, I want to get a list of times that would work for my group
- [ ] As a customer, I want to be able to ensure that I can choose how strict I would like the sorting to be
